### ISSUE TITLE
Add samples from each package example.

### ISSUE THREAD

**Issue by xavierchanth** [atsign-foundation/at_app_cli#69]
See atsign-foundation/at_widgets#270 for more information.

Packages:
- [x] at_backupkey_flutter #153 
- [x] at_chat_flutter #159 
- [x] at_common_flutter @nickelskevin do we need to include this one?
- [x] at_contacts_flutter #71 
- [x] at_contacts_group_flutter #161 
- [x] at_events_flutter #165 
- [x] at_follows_flutter - needs to be updated
- [x] at_invitation_flutter #167
- [x] at_location_flutter #167
- [x] at_notify_flutter #167
- [x] at_onboarding_flutter #71 
- [x] at_sync_ui_flutter #167
- [x] at_theme_flutter #167

**Comment by xavierchanth** [comment]
at_contacts_flutter and at_onboarding_flutter added in 4.2.0

**Comment by CemTitor** [comment]
at_backupkey_flutter added in 4.2.3

**Comment by CemTitor** [comment]
at_chat_flutter added in 4.2.3

**Comment by CemTitor** [comment]
at_contacts_group_flutter added in 4.2.3

**Comment by CemTitor** [comment]
at_events_flutter added in 4.2.3

**Comment by CemTitor** [comment]
- at_invitation_flutter
- at_location_flutter
- at_notify_flutter
- at_sync_ui_flutter
- at_theme_flutter
added in 4.2.3

**Comment by CemTitor** [comment]
Skipped at_common_flutter

**Comment by xavierchanth** [comment]
@CemTitor will you be working on at_follows_flutter or would you like me to pick it up?

**Comment by CemTitor** [comment]
@XavierChanth I think it would be better if you pick it up, thanks a lot
